baseURL = "https://stephaniehobson.ca"
languageCode = "en-us"
title = "Stephanie Hobson"
publishDir = "docs"
relativeURLs = true
[taxonomies]
  tag = "tags"
  year = "year"
  talk = "talks"
[author]
    name = "Stephanie Hobson"
